remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: lol-position-classification
description: >-
  Final project for DSC 80 at UCSD. Analyzed and classified player positions in League of Legends.
author: Ty Albao & Vu Le