remote_theme: pages-themes/dinky@v0.2.0
plugins:
  - jekyll-remote-theme

title: lol-position-classification
description: >-
  Final project for DSC 80 at UCSD. Analyzed and classified player positions in League of Legends.

# Change the author field to include all maintainers
author: "Ty Albao, Vu Le, [Person 3], [Person 4]"
