# Setup
title:               LoL Position Classification
tagline:             'Data Analysis'
description:         ''
url:                 'https://TyAlbao.github.io'
baseurl:             '/lol-position-classification/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name1:              Ty Albao
  name2:              Vu Le
  url1:               https://github.com/TyAlbao
  url2:               https://github.com/VuLe005
  email1:             #insert email
  email2:             kile@ucsd.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
