# Setup
title:               League of Legends Position Analysis and Classification
tagline:             
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Ty Albao
  url:               https://github.com/TyAlbao
  email:             markdotto@gmail.com
  
  name:              Vu Le
  url:               https://github.com/VuLe005
  email:             vul0015@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-remote-theme 

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y